let search = [
  "2d game development",
  "3d game development",
  "acca",
  "adhd",
  "anbima certification",
  "ap physics",
  "aws certificate cloud practitioner",
  "aws certification",
  "aws certified solution architecture associate",
  "academics writing",
  "accounting",
  "active directory",
  "aerospace engineering",
  "after effect",
  "agile",
  "algebra",
  "algorithm trading",
  "amazon aws",
  "amazon fba",
  "amazon kindly direct publishing",
  "anatomy",
  "android development",
  "anger managemant",
  "angular",
  "ansible",
  "anti-money laundering",
  "anxiety management",
  "apple",
  "apple keynote",
  "apple products basics",
  "aribnb hosting",
  "art history",
  "art theraphy",
  "articulate storyline",
  "audio creation book",
  "aurdino",
  "autism",
  "auto cad",
  "aws certigfied developer-associate",
  "b2b sales",
  "bpm bussiness process management",
  "bussiness communication",
  "bussiness writing",
  "banking",
  "basic fundamentals",
  "bass guitar",
  "binanace",
  "biology",
  "bitcoin",
  "bitcoin trading",
  "blockchain",
  "blogging",
  "body language",
  "bookkeeping",
  "btcoin",
  "bussines commuincation",
  "bussiness",
  "bussiness analysis",
  "bussiness analytics & intelligence",
  "bussiness development",
  "bussiness intelligence",
  "bussiness law",
  "bussiness model",
  "bussiness strategy",
  "bussiness analytics",
  "bussiness plan",
  "c language",
  "c#",
  "c++",
  "cams certification",
  "cbt cognitive behavioral threaphy",
  "cbt cognitive behavioural theraphy",
  "cbt congitive behavioural therpahy",
  "cfa",
  "css",
  "calculus",
  "canva",
  "career development",
  "certified managemant accountant",
  "chakra",
  "chemaical engineering",
  "chemistry",
  "child philosphy",
  "childhood trauma heading",
  "childhood trauma healing",
  "christianity",
  "cisco ccna",
  "civil engineering",
  "coaching",
  "cold retial",
  "comminication skills",
  "communcicarion skills",
  "communication",
  "communication skills",
  "comptia a+",
  "comptia network",
  "comptia secuirity",
  "complaince",
  "confidence",
  "conflict management",
  "construction",
  "construction estimation",
  "contact mnagement",
  "contract law",
  "contract low",
  "control systems",
  "corporate finanace",
  "corporate finance",
  "counseling",
  "cpcm",
  "creative writing",
  "creativity",
  "critical thinking",
  "cryptocurrency",
  "cryptocurrency blockchain",
  "crystal energy",
  "customer service",
  "customer success management",
  "cyber secuirity",
  "docker",
  "dance",
  "dart laguage",
  "data analysis",
  "data en,try skills",
  "data modelling",
  "data protection",
  "data science",
  "data vissualization",
  "database administration",
  "database design & development",
  "day trading",
  "deep learning",
  "design thinking",
  "development",
  "devops",
  "digital marketing",
  "digital photography",
  "digital transformation",
  "discrete math",
  "diversity & inculsion",
  "django",
  "dropshipping",
  "drums",
  "eft",
  "eplan electric pb",
  "esl",
  "early childhod education",
  "early childhood education",
  "ecommerce",
  "ecommerce1",
  "econometric",
  "economics",
  "electric vehical",
  "electrical engineering",
  "electronics",
  "email etiqutte",
  "embedded c",
  "embedded systems",
  "emotional intelligence",
  "employement law",
  "energy healing",
  "enginnering",
  "english conversation",
  "english grammer",
  "english language",
  "english literature",
  "english vocabulary",
  "enterpreneruship",
  "enterprenurship",
  "enterprenurship fundamantals",
  "enterprenurship fundamentals",
  "esoteric practices",
  "estl",
  "ethical hacking",
  "excel",
  "excel analysis",
  "excel dashboard",
  "excel formulas and functions",
  "excel vba",
  "eye movement desensitization and reprocessing",
  "eye movement destinatizition and reprocessing",
  "fpga",
  "fashion",
  "fiction writing",
  "finace",
  "finanacial accounting",
  "finance  fundamentals",
  "finance accounting",
  "finance ffundamentals",
  "finance fundamantals",
  "finance fundamentals",
  "finance set & exam prep",
  "financial accounting",
  "financial analysis",
  "financial fundamentals",
  "financial managemant",
  "financial marketing",
  "financial markets",
  "financial modelling",
  "financial modelling & analysis",
  "financial planning",
  "financial statement",
  "fitness",
  "fixed income secuirirties",
  "focus mastery",
  "forex",
  "fraud analytics",
  "freelance writing",
  "freelancing",
  "french language",
  "fright broker",
  "funderising",
  "gdpr",
  "game development",
  "game devolopment fundamentals",
  "geometry",
  "german language",
  "gmail productivity",
  "go language",
  "goal setting",
  "goods and services",
  "google",
  "google applesheet",
  "google data studio",
  "google docs",
  "google drive",
  "google flutter",
  "google office",
  "google workspace",
  "google sheets",
  "grnat writing",
  "guitar",
  "html5",
  "habits",
  "happiness",
  "hardware",
  "harmonica",
  "health and fitness",
  "healthcare it",
  "hiring",
  "home bussiness",
  "hr analysis",
  "human resources",
  "humanities",
  "hypnotheraphy",
  "ifrs",
  "imovies",
  "it & software",
  "it certififcation",
  "it networking fundamantals",
  "industry",
  "infulence",
  "innovation",
  "instructinal design",
  "instructional design",
  "instruments",
  "internal auditing",
  "interviewing skills",
  "investing",
  "investing and trading",
  "investment banking",
  "iso 9001",
  "japanese language",
  "java",
  "javascript",
  "job search",
  "journalism",
  "keyoard instument",
  "kotlin",
  "kubernetes",
  "lpic-1:lnux administration",
  "language learning",
  "law",
  "lead generation",
  "leadership",
  "leaked concentration",
  "lean",
  "learning disability",
  "learning strategies",
  "life coach industry",
  "life coach training",
  "life coaching training",
  "linear algebra",
  "linke in",
  "linked in",
  "linkedin",
  "linux",
  "linux administration",
  "linux commandline",
  "listening skills",
  "live purpose",
  "logistics management",
  "love",
  "my sql",
  "mac basics",
  "mac pages",
  "machine learning",
  "macroeconomics",
  "manage timing",
  "managemant skills",
  "management",
  "management co nsulting",
  "management skills",
  "manager training",
  "manifestation and law of attraction",
  "manifestation and law of attraction of mindfullness",
  "marriage",
  "master your emotions",
  "math",
  "mechanical engineering",
  "media",
  "medical device development",
  "medication",
  "mediia",
  "meditation",
  "meetings",
  "memory",
  "memory & study skills",
  "microbiology",
  "microcontrollers",
  "microeconomics",
  "microsoft",
  "microsoft az-900",
  "microsoft certification",
  "microsoft office",
  "microsoft power bi",
  "microsoft word",
  "mind mapping",
  "mindfullness",
  "mindfulness",
  "mobile development",
  "mobile game development",
  "money management tools",
  "moodle",
  "mortage",
  "motion grpahics",
  "motivation",
  "music",
  "nft",
  "nft (non- fungible tokens)",
  "nvivo",
  "negotiaition",
  "network & secuirity",
  "network secuirity",
  "neural networks",
  "neuro linguistic programming",
  "neuro linguistic progrmmaing",
  "neuro-linguistic program",
  "neuroplasticity",
  "neuroscience",
  "node.js",
  "notary bussines",
  "notion workspace",
  "novel writing",
  "numbers for mac",
  "numerology",
  "office productivity",
  "oil and gas industry",
  "on camera confidence",
  "online bussiness",
  "online business",
  "online course creation",
  "online education",
  "operating sysytems and servers",
  "operations",
  "options trading",
  "oracle",
  "oracle certification",
  "oracle data integrator",
  "oracle database",
  "oracle priminvera",
  "oracle sql",
  "organization",
  "orthodontics",
  "other bussiness",
  "other finance & accounting",
  "other it & software",
  "other office productivity",
  "other personal development",
  "other teaching & academics",
  "php",
  "pi/sql",
  "plc",
  "pmi pombook",
  "pmi-acp",
  "pmp",
  "parenting",
  "parenting & relationship",
  "parenting realtionship",
  "passiva income",
  "passive income",
  "patent",
  "penetration testing",
  "personal brand building",
  "personal building",
  "personal development",
  "personal finance",
  "personal network",
  "personal networking",
  "personal productivity",
  "personal success",
  "personal transformation",
  "persuation",
  "peuro linguistic programming",
  "philosophy",
  "photography and video",
  "physics",
  "piano",
  "piano chords",
  "piping",
  "pivot tables",
  "podcasting",
  "popular topics",
  "positive psycology",
  "possitive psychology",
  "power point",
  "powerpoint",
  "powershell",
  "presentation skills",
  "private equity",
  "probability",
  "procastination",
  "product management",
  "programming laguage",
  "programming fub=ndamantals",
  "project management",
  "project planning",
  "project risk management",
  "proofreading",
  "property management",
  "psychic",
  "psycology",
  "public speaking",
  "punctuation",
  "pyhton",
  "python",
  "quality management",
  "quantative finanace",
  "quick book pro",
  "quick books",
  "quickbook online",
  "quickbooks online",
  "quickbooks pro",
  "r laguage",
  "raspberrypy",
  "react",
  "react native",
  "real estate",
  "real estate investing",
  "realestate marketing",
  "recruiting",
  "regression analysis",
  "reiki",
  "relationship building",
  "relaxation",
  "research methods",
  "research paper writing",
  "resume and cv (writing)",
  "resume and cv writing",
  "risk management",
  "robotics",
  "sap",
  "sap abrap",
  "sap fico",
  "sap hcm",
  "sap mm",
  "sap project",
  "sap s/ 4hana",
  "sap sd",
  "sat",
  "seo",
  "sql",
  "sales",
  "sales skills",
  "salesforce",
  "sarbence oxeley",
  "science",
  "screen writing",
  "screenwriting",
  "scrum",
  "self esteem & cofidencs",
  "self-esteem",
  "selling on amazon",
  "service now",
  "shamanisim",
  "shamanism",
  "shell scripting",
  "shopify",
  "shopify dropshooting",
  "siemens tia portal",
  "sign language",
  "six sigma",
  "six sigma black belt",
  "six sigma green belt",
  "six sigma white belt",
  "six sigma yellow belt",
  "social skills",
  "software architecture",
  "solar energy",
  "sound theraphy",
  "spanish language",
  "spanosh language",
  "speed reading",
  "spiritual heeling",
  "spring framework",
  "spritual healing",
  "sprituality",
  "stata",
  "statistics",
  "stock trading",
  "story telling",
  "storytelling",
  "stratup",
  "stree managemant",
  "study skills",
  "supply chain",
  "swift",
  "swiftui",
  "togaf 9 certified",
  "togaf 9 foundation",
  "tableau",
  "tarot reading",
  "tasnction",
  "tax preparation",
  "taxes",
  "teacher training",
  "teaching english",
  "teaching online",
  "teaching andd academics",
  "technical analysis",
  "the bible",
  "time management",
  "trade and commerce",
  "train the trainer",
  "trigonometry",
  "trucking",
  "typing",
  "ukulele",
  "unity",
  "unreal engine blueprints",
  "violin",
  "vlaue added tax",
  "voice acting",
  "voice over",
  "voice training",
  "web development",
  "windows server",
  "writing",
  "writing a book",
  "writing block",
  "xero",
  "ios development",
  "macos",
  "ouples counselling",
  "personal auditing",
  "reiligion & sprituality",
];

// search.sort();
// let unique = [...new Set(search)];
// for (let i = 0; i < search.length; i++) {
//   search[i].trim();
// }
// const results = search.map((element) => {
//   return element.trim().toLowerCase();
// });
// console.log(search);
import searchP from "./searchProd.js";
function autocomplete(inp, arr) {
  var currentFocus;
  inp.addEventListener("input", function (e) {
    document.querySelector(".autocomplete").innerHTML = "";
    var a,
      b,
      i,
      val = this.value;
    closeAllLists();
    if (!val) {
      return false;
    }
    currentFocus = -1;
    a = document.createElement("DIV");
    a.setAttribute("id", this.id + "autocomplete-list");
    a.setAttribute("class", "autocomplete-items");
    this.parentNode.appendChild(a);
    for (i = 0; i < arr.length; i++) {
      if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
        b = document.createElement("div");
        b.classList.add("suggestions");
        b.innerHTML = `<img class="icon" id="res-icon" width="10px" src="assets/search.png" alt=""><strong>${arr[
          i
        ].substr(0, val.length)}</strong>`;
        b.innerHTML += arr[i].substr(val.length);
        b.innerHTML += `<input type='hidden' value="${arr[i]}">`;
        b.addEventListener("click", function (e) {
          inp.value = this.getElementsByTagName("input")[0].value;
          closeAllLists();
          searchP(inp.value);
        });
        document.querySelector(".autocomplete").append(b);
      }
    }
  });
  inp.addEventListener("keydown", function (e) {
    var x = document.getElementById(this.id + "autocomplete-list");
    if (x) x = x.getElementsByTagName("div");
    if (e.keyCode == 40) {
      currentFocus++;
      addActive(x);
    } else if (e.keyCode == 38) {
      currentFocus--;
      addActive(x);
    } else if (e.keyCode == 13) {
      e.preventDefault();
      if (currentFocus > -1) {
        if (x) x[currentFocus].click();
      }
    }
  });
  function addActive(x) {
    if (!x) return false;
    removeActive(x);
    if (currentFocus >= x.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = x.length - 1;
    x[currentFocus].classList.add("autocomplete-active");
  }
  function removeActive(x) {
    for (var i = 0; i < x.length; i++) {
      x[i].classList.remove("autocomplete-active");
    }
  }
  function closeAllLists(elmnt) {
    var x = document.getElementsByClassName("autocomplete-items");
    for (var i = 0; i < x.length; i++) {
      if (elmnt != x[i] && elmnt != inp) {
        x[i].parentNode.removeChild(x[i]);
      }
    }
  }
  document.addEventListener("click", function (e) {
    closeAllLists(e.target);
  });
}
autocomplete(document.getElementById("search"), search);
document.getElementById("search").addEventListener("keyup", (e) => {
  if (e.key == "Enter") {
    searchP(document.getElementById("search").value);
  }
});
